services:
  - type: web
    name: supportchat-middleware
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: ZULIP_BOT_EMAIL
        value: placeholder
      - key: ZULIP_API_KEY
        value: placeholder

