services:
  - type: web
    name: supportchat-middleware
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: ZULIP_BOT_EMAIL
        value: your-bot@zulip-domain
      - key: ZULIP_API_KEY
        value: your-zulip-bot-api-key
      - key: ZULIP_SITE_URL
        value: https://chat-test.filmlight.ltd.uk
      - key: GLITCH_RELAY_URL
        value: https://peppered-bubbly-glade.glitch.me/send


